[[redirects]]
	from="/*"
	to="index.html"
	status=200

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
